[tool.poetry]
name = "tomba"
version = "0.1.1a1"
description = "Identifique localizaÃ§Ãµes brasileiras em um texto ğŸ˜"
authors = ["Dados Abertos de Feira <dadosabertosdefeira+gh@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "tomba"},
    {include = "models"},
]
include = ["models/"]

[tool.poetry.dependencies]
python = "^3.8"
spacy = ">=3.0.0"
jupyter = "^1.0.0"
pandas = "^1.2.1"
setuptools = "^53.0.0"
wheel = "^0.36.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
black = "^20.8b1"
pre-commit = "^2.9.3"
flake8 = "^3.8.4"
httpx = "^0.16.1"
beautifulsoup4 = "^4.9.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
