[tool.poetry]
name = "tomba"
version = "0.1.0"
description = "Identifique localizaÃ§Ãµes brasileiras em um texto ğŸ˜"
authors = ["Dados Abertos de Feira <dadosabertosdefeira+gh@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
spacy = "^2.3.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
black = "^20.8b1"
pre-commit = "^2.9.3"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
